# Generated by Django 5.2.6 on 2025-10-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registration_delete_regestration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the event poster', null=True, upload_to='event_images/'),
        ),
    ]
